create table student(
    id int primary key generated by default as identity,
    name varchar(50) not null,
    surname varchar(50) not null
  );
create table course(
                       id int primary key generated by default as identity,
                       name varchar(50) not null
);
create table grade(
    id int primary key generated by default as identity,
    value int not null,
    student_id int not null,
    course_id int not null,
    foreign key(student_id) references student(id),
    foreign key(course_id) references course(id)
);

insert into student(name,surname)
values
('Swen','Swenson'),('John','Jonson'),('Nick','Nicolson');

insert into course(name)
values
    ('Math'),('Physic'),('English')('Programming');

insert into grade(value,student_id,course_id)
values
    ('5','1','1'),('4','1','2'),
    ('5', 2, '3'),('4','2','4');